-- Базовые настройки
vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.opt.shiftwidth = 4
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.cursorline = true
vim.o.termguicolors = true
vim.cmd('hi Normal guibg=NONE')
vim.opt.clipboard = "unnamedplus"
